M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Thu 10 Oct 2024 07:54:35 AM UTC
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-10T07:54:35+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.95Y-1.95
X2.95Y-4.95
X6.8Y-1.95
X6.8Y-4.95
T0
M30
